/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_dashboard;

import config.PanelPrinter;
import config.dbconnector;
import config.session;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import jb.loginform;
import net.proteanit.sql.DbUtils;
import tickets.ticket_panel;

/**
 *
 * @author Dela Cuesta
 */
public class user_booking extends javax.swing.JFrame {

    /**
     * Creates new form user_reservation
     */
    public user_booking() {
        initComponents();
    //    cb();
        displayData();
    
    }
    Color navcolor =  new Color(204,204,204);
    Color hovercolor =  new Color(0,0,0);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        view = new javax.swing.JMenuItem();
        viewPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        c_name = new javax.swing.JLabel();
        m_price = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        r_year = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        runtime = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        director = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Reserve = new java.awt.Button();
        jLabel31 = new javax.swing.JLabel();
        m_status = new javax.swing.JLabel();
        book = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        booknow = new java.awt.Button();
        qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        m_price1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        p_add1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        p_add2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        p_add6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cashiername = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p_add7 = new javax.swing.JPanel();
        p_add5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_movies = new javax.swing.JTable();

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        popUp.add(view);

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 57, 77)));
        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Movie Price:");
        viewPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, 20));

        c_name.setText("Cinema Name");
        viewPanel.add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 120, 20));

        m_price.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        m_price.setForeground(new java.awt.Color(255, 2, 2));
        m_price.setText("Movie Price");
        viewPanel.add(m_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 140, 20));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Release Year:");
        viewPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 80, 20));

        title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Movie Title");
        viewPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 40));

        r_year.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        r_year.setForeground(new java.awt.Color(27, 57, 77));
        r_year.setText("Release Year");
        viewPanel.add(r_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 170, 20));

        genre.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        genre.setForeground(new java.awt.Color(27, 57, 77));
        genre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genre.setText("Genre");
        viewPanel.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 20));

        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 57, 77)));
        imagePanel.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        viewPanel.add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 170));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("  Movie Details");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 470, 50));

        viewPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Run Time:");
        viewPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 70, 20));

        runtime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        runtime.setForeground(new java.awt.Color(27, 57, 77));
        runtime.setText("Run Time");
        viewPanel.add(runtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 70, 20));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Director:");
        viewPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 80, 20));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Seats:");
        viewPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 80, 20));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Cinema:");
        viewPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 80, 20));

        director.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        director.setForeground(new java.awt.Color(27, 57, 77));
        director.setText("Director Name");
        viewPanel.add(director, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 150, 20));

        seats.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        seats.setForeground(new java.awt.Color(27, 57, 77));
        seats.setText("Seats");
        viewPanel.add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 100, 20));
        viewPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 660, 10));

        Reserve.setBackground(new java.awt.Color(0, 0, 0));
        Reserve.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Reserve.setForeground(new java.awt.Color(255, 255, 255));
        Reserve.setLabel("Book Ticket");
        Reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveActionPerformed(evt);
            }
        });
        viewPanel.add(Reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 120, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Status:");
        viewPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 80, 20));

        m_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        m_status.setForeground(new java.awt.Color(27, 57, 77));
        m_status.setText("Status");
        viewPanel.add(m_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 100, 20));

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 57, 77)));
        book.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/camera-movie.png"))); // NOI18N
        title1.setText("TITLE");
        jPanel6.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));

        book.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));
        book.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 370, 10));

        booknow.setBackground(new java.awt.Color(0, 0, 0));
        booknow.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        booknow.setForeground(new java.awt.Color(255, 255, 255));
        booknow.setLabel("Book");
        booknow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknowActionPerformed(evt);
            }
        });
        book.add(booknow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 30));
        book.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Enter Quantity:");
        book.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Price per ticket:");
        book.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 370, 30));

        m_price1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        m_price1.setForeground(new java.awt.Color(255, 2, 2));
        m_price1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_price1.setText("Movie Price");
        book.add(m_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 370, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_add1.setBackground(new java.awt.Color(0, 0, 0));
        p_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add1MouseExited(evt);
            }
        });
        p_add1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-dashboard-24 (1).png"))); // NOI18N
        jLabel8.setText("DASHBOARD");
        p_add1.add(jLabel8);
        jLabel8.setBounds(0, 0, 190, 40);

        jPanel2.add(p_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 178, 190, 41));

        p_add2.setBackground(new java.awt.Color(0, 0, 0));
        p_add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add2MouseExited(evt);
            }
        });
        p_add2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-reports-24.png"))); // NOI18N
        jLabel13.setText("VIEW REPORTS");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        p_add2.add(jLabel13);
        jLabel13.setBounds(-10, 0, 190, 40);

        jPanel2.add(p_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 225, 186, 41));

        p_add6.setBackground(new java.awt.Color(0, 0, 0));
        p_add6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add6MouseExited(evt);
            }
        });
        p_add6.setLayout(null);
        jPanel2.add(p_add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 456, 196, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-admin-50.png"))); // NOI18N
        jLabel7.setText("admin");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 52, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CASHIER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 90, -1, 17));

        cashiername.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cashiername.setForeground(new java.awt.Color(255, 0, 0));
        cashiername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashiername.setText("Name");
        jPanel2.add(cashiername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 31));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-log-out-24.png"))); // NOI18N
        jLabel18.setText("Log out");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 359, 186, 40));

        p_add7.setBackground(new java.awt.Color(0, 0, 0));
        p_add7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add7MouseExited(evt);
            }
        });
        p_add7.setLayout(null);

        p_add5.setBackground(new java.awt.Color(0, 0, 0));
        p_add5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add5MouseExited(evt);
            }
        });
        p_add5.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-ticket-purchase-30.png"))); // NOI18N
        jLabel19.setText("BOOKING");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        p_add5.add(jLabel19);
        jLabel19.setBounds(-20, 0, 190, 40);

        p_add7.add(p_add5);
        p_add5.setBounds(0, 0, 176, 40);

        jPanel2.add(p_add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 313, 176, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-ticket-26.png"))); // NOI18N
        jLabel16.setText("ISSUED TICKET");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 570));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOKING");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 40, 630, 29);

        tbl_movies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_moviesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_moviesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_movies);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 90, 590, 230);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
    public void cb(){
        dbconnector connect = new dbconnector();
        
        try {
            m_id.addItem("");
            ResultSet rs = connect.getData("SELECT * FROM tbl_movies");
            while(rs.next()){
                m_id.addItem(rs.getString("m_id"));
           
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void displayData() {
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
    date.setText(sdf.format(d));
    try {
        dbconnector connector = new dbconnector();
        ResultSet rs = connector.getData("SELECT * FROM tbl_movies m JOIN tbl_cinema c ON m.c_id = c.c_id WHERE m.m_id = " + m.getSelectedItem());
        if (rs.next()) {
            title.setText(rs.getString("m.title"));
            cinema.setText(rs.getString("c.c_name")); 
            run_time.setText(rs.getString("m.run_time"));
            m_price.setText(rs.getString("m.r_year"));
            director.setText(rs.getString("m.director"));
            genre.setText(rs.getString("m.genre"));
            m_price.setText(rs.getString("m.m_price"));
        }
        rs.close();
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}
**/
    
    public void displayData(){
        try{
            dbconnector connector = new dbconnector();
            ResultSet rs = connector.getData("SELECT m_id, title,genre,run_time,m_price,"
                    + "movie_status FROM tbl_movies WHERE movie_status = 'Active'");
            tbl_movies.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
    }
   
    
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
      user_booking ads = new user_booking();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void p_add7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add7MouseExited

    private void p_add7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add7MouseEntered

    private void p_add7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add7MouseClicked

    private void p_add5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add5MouseExited

    private void p_add5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add5MouseEntered

    private void p_add5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add5MouseClicked

        user_Ticket ads = new user_Ticket();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_add5MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        session sess = session.getInstance();
        
        int userId = sess.getUid();
        
        logEvent(userId, "LOGOUT", "User logged out");
        
        
        loginform ads = new loginform();
        JOptionPane.showMessageDialog(null,"Logout Success!");
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void p_add6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add6MouseExited
        p_add6.setBackground(hovercolor);
    }//GEN-LAST:event_p_add6MouseExited

    private void p_add6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add6MouseEntered
        p_add6.setBackground(navcolor);
    }//GEN-LAST:event_p_add6MouseEntered

    private void p_add6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add6MouseClicked
        loginform ads = new loginform();
        JOptionPane.showMessageDialog(null,"Logout Success!");
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_add6MouseClicked

    private void p_add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseExited

    private void p_add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseEntered

    private void p_add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseClicked

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited

    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        user_Reports ads = new user_Reports ();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void p_add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseExited
        p_add1.setBackground(hovercolor);
    }//GEN-LAST:event_p_add1MouseExited

    private void p_add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseEntered
        p_add1.setBackground(navcolor);
    }//GEN-LAST:event_p_add1MouseEntered

    private void p_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseClicked
        user_dashboard ads = new user_dashboard();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_add1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        user_Ticket ads = new user_Ticket();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
session sess = session.getInstance();

        if(sess.getUid() == 0){
            JOptionPane.showMessageDialog(null, "No Account, Log in First! ","Notice", JOptionPane.ERROR_MESSAGE);
            loginform ads = new loginform();
            ads.setVisible(true);
            this.dispose();
        }else{
            cashiername.setText(sess.getFname() + " " + sess.getLname());
            try{
                dbconnector dbc = new dbconnector();
                ResultSet rs = dbc.getData("SELECT * FROM tbl_u WHERE u_id = '"+sess.getUid()+"'");

                if(rs.next()){

                }

            }catch(SQLException ex){
                System.out.println(""+ex);

            }

        }
       
    }//GEN-LAST:event_formWindowActivated

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       int rowIndex = tbl_movies.getSelectedRow();

if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select an Item!");
} else {
    try {
        dbconnector connector = new dbconnector();
        TableModel tbl = tbl_movies.getModel();
        ResultSet resultSet = connector.getData("SELECT m.*, c.c_name, c.c_seats FROM tbl_movies m JOIN tbl_cinema c ON m.c_id = c.c_id WHERE m.m_id = '" + tbl.getValueAt(rowIndex, 0) + "'");

        if (resultSet.next()) {
            title1.setText(" "+resultSet.getString("title"));
            title.setText(resultSet.getString("title"));
            genre.setText(resultSet.getString("genre"));
            c_name.setText(resultSet.getString("c_name"));
            r_year.setText(resultSet.getString("r_year"));
            m_price.setText("$"+resultSet.getString("m_price"));
            m_price1.setText("$"+resultSet.getString("m_price"));
            runtime.setText(resultSet.getString("run_time"));
            director.setText(resultSet.getString("director"));
            m_status.setText(resultSet.getString("movie_status"));
            seats.setText(resultSet.getString("c_seats"));

            JOptionPane.showOptionDialog(null, viewPanel, "",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, new Object[]{}, null);
        }

        resultSet.close();
    } catch (SQLException ex) {
        System.out.println("Error: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_viewActionPerformed

    private void tbl_moviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_moviesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_moviesMouseClicked

    private void tbl_moviesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_moviesMousePressed
        if (SwingUtilities.isRightMouseButton(evt)) {
            popUp.show(tbl_movies, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbl_moviesMousePressed

    private void ReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveActionPerformed
                JOptionPane.showOptionDialog(null, book, "",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, new Object[]{}, null);     
    }//GEN-LAST:event_ReserveActionPerformed

    private void booknowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknowActionPerformed
        ticket_panel t = new ticket_panel();
        t.title.setText(title.getText());
        PanelPrinter pPrint = new PanelPrinter(t.page);
        pPrint.printPanel();
    }//GEN-LAST:event_booknowActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void logEvent(int userId, String event, String description) {
   
        dbconnector dbc = new dbconnector();
        PreparedStatement pstmt = null;
        
    try {
     

        String sql = "INSERT INTO tbl_logs (log_timestamp, log_event, u_id, log_descript) VALUES (?, ?, ?, ?)";
        pstmt = dbc.connect.prepareStatement(sql);
        pstmt.setTimestamp(1, new Timestamp(new Date().getTime()));
        pstmt.setString(2, event);
        pstmt.setInt(3, userId);
        pstmt.setString(4, description);

        pstmt.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
       
    }
    
 }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Reserve;
    private javax.swing.JPanel book;
    private java.awt.Button booknow;
    private javax.swing.JLabel c_name;
    private javax.swing.JLabel cashiername;
    private javax.swing.JLabel director;
    private javax.swing.JLabel genre;
    public javax.swing.JLabel image;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel m_price;
    private javax.swing.JLabel m_price1;
    private javax.swing.JLabel m_status;
    private javax.swing.JPanel p_add1;
    private javax.swing.JPanel p_add2;
    private javax.swing.JPanel p_add5;
    private javax.swing.JPanel p_add6;
    private javax.swing.JPanel p_add7;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel r_year;
    private javax.swing.JLabel runtime;
    private javax.swing.JLabel seats;
    private javax.swing.JTable tbl_movies;
    public javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JMenuItem view;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
